import { Employee, Department, Task, AuditLog, Role } from '../types';
// Fix: Use the new supabase client location as services/supabaseClient.ts is deprecated
import { supabase } from '../lib/supabase/client';
import { MOCK_EMPLOYEES, MOCK_DEPARTMENTS, MOCK_TASKS } from '../constants';

// Helper to map DB response to App types if necessary
// For now assuming DB structure matches Typescript interfaces loosely (snake_case in DB vs camelCase in TS)

export const DataService = {
  // --- AUTH ---
  login: async (email: string, password: string): Promise<{ user: any, error: any }> => {
    // 1. Try to sign in with Supabase Auth
    const { data, error } = await supabase.auth.signInWithPassword({
      email,
      password,
    });
    
    if (error) return { user: null, error };

    // 2. Fetch extra employee details
    if (data.user) {
      // Assuming 'employees' table has an 'email' column that matches
      const { data: empData } = await supabase
        .from('employees')
        .select('*')
        .eq('email', email)
        .single();
        
      return { 
        user: { 
            ...data.user, 
            employeeDetails: empData || { 
                fullName: 'Admin', 
                role: Role.ADMIN, 
                avatarUrl: '',
                departmentId: ''
            } 
        }, 
        error: null 
      };
    }
    
    return { user: data.user, error: null };
  },

  logout: async () => {
    await supabase.auth.signOut();
  },

  getUserSession: async () => {
    const { data } = await supabase.auth.getSession();
    return data.session;
  },

  // --- EMPLOYEES ---
  getEmployees: async (): Promise<Employee[]> => {
    const { data, error } = await supabase.from('employees').select('*');
    if (error) {
      console.error('Error fetching employees:', error);
      return MOCK_EMPLOYEES; // Fallback for demo if DB not connected
    }
    return data as Employee[];
  },

  saveEmployee: async (employee: Employee): Promise<Employee> => {
    // Note: 'id' might be auto-generated by DB or UUID from Supabase Auth
    // We try to upsert based on ID
    const { data, error } = await supabase
      .from('employees')
      .upsert(employee)
      .select()
      .single();
      
    if (error) {
       console.error('Error saving employee:', error);
       throw error;
    }
    return data as Employee;
  },

  deleteEmployee: async (id: string): Promise<void> => {
    const { error } = await supabase.from('employees').delete().eq('id', id);
    if (error) console.error('Error deleting employee:', error);
  },

  // --- DEPARTMENTS ---
  getDepartments: async (): Promise<Department[]> => {
    const { data, error } = await supabase.from('departments').select('*');
    if (error) return MOCK_DEPARTMENTS;
    return data as Department[];
  },

  saveDepartment: async (dept: Department): Promise<Department> => {
    const { data, error } = await supabase.from('departments').upsert(dept).select().single();
    if(error) throw error;
    return data as Department;
  },

  deleteDepartment: async (id: string): Promise<void> => {
    await supabase.from('departments').delete().eq('id', id);
  },

  // --- TASKS ---
  getTasks: async (deptId?: string): Promise<Task[]> => {
    let query = supabase.from('tasks').select('*');
    if (deptId) {
      query = query.eq('departmentId', deptId);
    }
    const { data, error } = await query;
    if (error) return MOCK_TASKS;
    return data as Task[];
  },

  saveTask: async (task: Task): Promise<Task> => {
    const { data, error } = await supabase.from('tasks').upsert(task).select().single();
    if(error) throw error;
    return data as Task;
  },

  deleteTask: async (id: string): Promise<void> => {
    await supabase.from('tasks').delete().eq('id', id);
  },

  // --- LOGS ---
  getLogs: async (): Promise<AuditLog[]> => {
    const { data, error } = await supabase
        .from('audit_logs')
        .select('*')
        .order('timestamp', { ascending: false })
        .limit(50);
    if(error) return [];
    return data as AuditLog[];
  }
};